web/__init__.py
from datetime import timedelta
from flask import Flask, render_template
from flask_minify import Minify
from werkzeug.middleware.proxy_fix import ProxyFix

from web import views
from web.cache import cache

config = {
    "SEND_FILE_MAX_AGE_DEFAULT": timedelta(days=30),
}

# Initialize application.
app = Flask(__name__)

# Configure application.
app.config.from_mapping(config)
Minify(app=app)
cache.init_app(app)
app.register_blueprint(views.mod)
app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1, x_prefix=1)

@app.errorhandler(404)
def not_found(error):
    return render_template('error.html'), 404

@app.errorhandler(500)
def internal_error(error):
    return render_template('error.html'), 500

web/views.py
from flask import Blueprint, render_template, url_for, redirect
from web.cache import cache

mod = Blueprint('views', __name__)

@mod.route('/')
@cache.cached()
def homepage():
    return render_template("index.html")

@mod.route('/work')
@cache.cached()
def work():
    return render_template("work.html")

@mod.route('/projects')
@cache.cached()
def projects():
    return render_template("projects.html")

@mod.route('/research')
@cache.cached()
def research():
    return render_template("research.html")

@mod.route('/resume')
@mod.route('/resume.pdf')
@cache.cached()
def resume():
    return redirect(url_for('static', filename='rouly_resume.pdf'))

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block pagetitle %}
michel rouly &middot; {home}
{% endblock %}

{% block content %}

<p>
  My name is Jean Michel Rouly. I am an undergraduate at 
  <a href="http://www.gmu.edu">George Mason University</a> 
  in Computer Science, with research interests in 
  Computational Linguistics and Data Mining. I currently
  serve as president of the George Mason
  <a href="http://srct.gmu.edu">Student-Run Computing and Technology</a>
  organization.
</p>

<p>
  This summer 2013 I was engaged as an undergraduate researcher with the
  <a href="http://www.fit.edu">Florida Institute of Technology</a> 
  and the 
  <a href="http://www.nsf.gov">National Science Foundation</a> 
  conducting research into machine learning in theory and 
  application with the 
  <a href="http://www.amalthea-reu.org">Amalthea REU</a>
  program.
</p>

<p>
  Please view my <a href="{% url 'work' %}">work</a>,
  <a href="{% url 'projects' %}">projects</a>,
  <a href="{% url 'research' %}">research</a>, and
  <a href="{% url 'community' %}">community</a> pages or my
  <a href="/resume.pdf">résumé</a> for more information.
</p>

{% endblock %}

web/templates/base.html
<!DOCTYPE HTML>
<html lang="en-US">

  <head>

    <title>Michel Rouly</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.png') }}" />

    <meta charset="UTF-8">
    <meta name="robots" content="all">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="keywords" content="Michel Rouly, Jean, Michel, Rouly, computer science, research, software, George Mason University">
    <meta name="description" content="Michel Rouly's personal website.">
    <meta name="author" content="Michel Rouly">

  </head>

  <body>
    <div id="container">

      <div id="banner">
        <h1>
          <a href="{{ url_for('views.homepage') }}"><img src="{{ url_for('static', filename='img/jrouly2.png') }}" id="profile" alt="jrouly2"></a>
          <a href="{{ url_for('views.homepage') }}" id="name">michel rouly</a> /
          <span id="pagetitle">{% block pagetitle %}{% endblock %}</span>
        </h1>
      </div>

      <ul id="nav">
        <li><a href="{{ url_for('views.homepage') }}">home</a></li>

        <li class="separator">portfolio</li>

        <li><a href="{{ url_for('views.work') }}">work</a></li>
        <li><a href="{{ url_for('views.projects') }}">projects</a></li>
        <li><a href="{{ url_for('views.research') }}">research</a></li>
        <li><a href="https://github.com/jrouly/bikes" target="_blank">bikes</a></li>

        <li class="separator">contact</li>

        <li><a href="{{ url_for('static', filename='rouly_resume.pdf') }}" target="_blank">resume</a></li>
        <li><a href="https://github.com/jrouly/" target="_blank">github</a></li>
        <li><a href="https://linkedin.com/in/michelrouly" target="_blank">linkedin</a></li>
        <li><a href="{{ url_for('static', filename='pgp.asc') }}" target="_blank">pgp</a></li>
      </ul>

      <div id="maincontent">
        {% block content %}

        {% endblock %}
      </div>

    </div>
  </body>
</html>

web/templates/index.html
{% extends 'base.html' %}

{% block pagetitle %}
home
{% endblock %}

{% block content %}
  <p>My name is Michel. I'm a software engineer and I like to work on projects that help people.</p>
  <p>When I'm not working I am probably on two wheels.</p>
  <p>This is my website.</p>
{% endblock %}

web/templates/projects.html
{% extends 'base.html' %}

{% block pagetitle %}
projects
{% endblock %}

{% block content %}

  <h2>Open Source</h2>

  <p>
    <code class="embedded-title"><a href="https://github.com/jrouly/sbt-artifactory" target="_blank">sbt-artifactory</a></code>
    A small <a href="https://www.scala-sbt.org/" target="_blank">sbt</a> plugin that adds a resolver for
    <a href="https://jfrog.com/artifactory/" target="_blank">Artifactory</a>. Makes resolving artifacts from and
    publishing artifacts to either internal Artifactory installations or the JFrog Artifactory cloud much simpler.
  </p>

  <p>
    <code class="embedded-title"><a href="https://github.com/jrouly/sbt-openapi-style-validator" target="_blank">sbt-openapi-style-validator</a></code>
    An <a href="https://www.scala-sbt.org/" target="_blank">sbt</a> plugin that supports validating
    <a href="https://www.openapis.org/" target="_blank">OpenAPI specification</a> files using
    <a href="https://github.com/OpenAPITools/openapi-style-validator" target="_blank"><code>openapi-style-validator</code></a>.
    Useful for validating OpenAPI correctness at build time or during CI.
  </p>

  <p>
    <code class="embedded-title"><a href="https://github.com/jrouly/sbt-openapi-diff" target="_blank">sbt-openapi-diff</a></code>
    An <a href="https://www.scala-sbt.org/" target="_blank">sbt</a> plugin that computes the diff between
    <a href="https://www.openapis.org/" target="_blank">OpenAPI specifications</a> using
    <a href="https://github.com/OpenAPITools/openapi-diff" target="_blank"><code>openapi-diff</code></a>. Useful for
    determining backwards compatibility between versions of the same OpenAPI specification, especially at build or
    release time.
  </p>

  <p>
    <code class="embedded-title"><a href="https://github.com/jrouly/sbt-docker" target="_blank">sbt-docker</a></code>
    Docker image of <a href="https://www.scala-sbt.org/" target="_blank">sbt</a> with pre-cached boot jars,
    emphasizing rapid startup time.
  </p>

  <p>
    <code class="embedded-title"><a href="https://github.com/jrouly/acs-language-survey" target="_blank">acs-language-survey</a></code>
    Analysis of the most common non-English and non-Spanish languages spoken per state in the US. Built using
    <a href="https://www.python.org/" target="_blank">Python</a> and
    <a href="https://pandas.pydata.org/" target="_blank">Pandas</a>.
  </p>

  <p>
    <code class="embedded-title"><a href="https://github.com/jrouly/traveling-beersman" target="_blank">traveling-beersman</a></code>
    Small graph data project to approximate a Traveling Salesman route between the local craft breweries in a city.
    Uses <a href="https://spark.apache.org" target="_blank">Apache Spark</a> with data sourced from
    <a href="https://beeradvocate.com" target="_blank">BeerAdvocate</a>.
  </p>

  <h2>George Mason University Honors College</h2>

  <p>
    <code class="embedded-title"><a href="https://github.com/jrouly/research-questions" target="_blank">research-questions</a></code>
    An open source platform for academic peer-review. Provides an intuitive system to facilitate scholarly
    conversations between students new to the research process. The conversation is facilitated by a rating and
    commenting system. An action logging system adds accountability to the student discussion, allowing faculty and
    mentors to moderate the service. Built on <a href="http://djangoproject.com" target="_blank">Django</a>.
  </p>

  <p>
    <code class="embedded-title"><a href="https://github.com/jrouly/reading-scholarly-articles" target="_blank">reading-scholarly-articles</a></code>
    A visual guide for students first entering the research process. It displays a
    collection of sample open source research articles in a variety of fields and highlights the various components
    that are common to that field. Built with <a href="http://getbootstrap.com" target="_blank">Bootstrap</a> and a
    great deal of <a href="http://jquery.com" target="_blank">JQuery</a>.
    Updates the <a href="https://www.ncsu.edu/" target="_blank">NCSU</a> library's
    <a href="https://www.lib.ncsu.edu/tutorials/scholarly-articles/" target="_blank">Anatomy of a Scholarly Article</a>
    project.
  </p>

  <h2>Student Run Computing and Technology</h2>

  <p>
    <code class="embedded-title"><a href="http://github.com/srct/go" target="_blank">go</a></code>
    SRCT Go is a university-branded URL shortening service. Go was originally written in Python with the low level
    <code><a href="https://modwsgi.readthedocs.io/en/master/" target="_blank">mod_wsgi</a></code> interface backed by
    <a href="http://mariadb.org/" target="_blank">MariaDB</a>. It has since been rewritten in
    <a href="http://djangoproject.com" target="_blank">Django</a>.
  </p>

  <p>
    <code class="embedded-title"><a href="http://github.com/srct/bookshare" target="_blank">bookshare</a></code>
    SRCT Bookshare is a textbook exchange platform for use by Mason students. Bookshare brings together buyers and
    sellers in a structured environment where items are organized by title, author, ISBN, and course number.
    Built on <a href="http://djangoproject.com" target="_blank">Django</a>. User accounts are maintained using an
    external LDAP database while listing data is managed by a backend
    <a href="http://mariadb.org/" target="_blank">MariaDB</a> database.
  </p>

{% endblock %}

web/templates/research.html
{% extends 'base.html' %}

{% block pagetitle %}
research
{% endblock %}

{% block content %}

  <!-- ------------------------------------------------------------------------------------------------------------ -->

  <h2>Masters Research Project</h2>

  <p>
    <strong>Project Title:</strong>&nbsp;Measuring Career Preparedness with Topic Modeling
  </p>

  <p>
    This self directed research was performed within the framework of the Georgia Tech
    <a href="https://omscs.gatech.edu/cs-6460-educational-technology" target="_blank">Educational Technology</a>
    research course. It explored the relationship between post-secondary education and the expectations of the
    workforce. Specifically it applied Topic Modeling to university course descriptions and industry job listings.
  </p>

  <p>
    The work utilized previous research performed at George Mason described below. The technologies used included
    <a href="https://www.scala-lang.org/" target="_blank">Scala</a>, <a href="https://akka.io/" target="_blank">Akka</a>,
    <a href="https://doc.akka.io/docs/alpakka/current/index.html" target="_blank">Alpakka</a>,
    Apache <a href="https://opennlp.apache.org/" target="_blank">OpenNLP</a> and
    <a href="https://spark.apache.org/" target="_blank">Spark</a>,
    <a href="https://www.elastic.co/" target="_blank">Elasticsearch</a>,
    <a href="https://github.com/playframework/playframework" target="_blank">Play</a>, and
    <a href="https://www.postgresql.org/" target="_blank">Postgres</a>.
  </p>

  <ul>
    <li><a href="{{ url_for('static', filename='dist/employability-paper.pdf') }}" target="_blank">Paper (pdf)</a></li>
    <li><a href="https://github.com/jrouly/employability" target="_blank">Code (GitHub)</a></li>
  </ul>

  <!-- ------------------------------------------------------------------------------------------------------------ -->

  <h2>Senior Design Research Project</h2>

  <p>
    <strong>Project Title:</strong>&nbsp;What Are We Teaching? Automated Evaluation of CS Curricula Content Using
    Topic Modeling
  </p>

  <p>
    This research was performed under the supervision of
    <a href="https://cs.gmu.edu/~hrangwal/" target="_blank">Huzefa Rangwala</a> at George Mason University. We explored
    the application of Topic Modeling to textual university curriculum data, specifically course descriptions.
    Automatically extracting content from this corpus allows for larger-scale analysis of university curricula than
    would be possible with manual inspection.
  </p>

  <p>
    In addition to extracting topics from course documents, I independently developed an easy-to-use, web-based
    visualization platform to display the results of information extraction and analysis. The visualization tool is
    built with <a href="https://flask.pocoo.org" target="_blank">Flask</a>.
  </p>

  <ul>
    <li><a href="https://doi.org/10.1145/2787622.2787723" target="_blank">ACM Digital Library</a></li>
    <li><a href="{{ url_for('static', filename='dist/trajectory-paper.pdf') }}" target="_blank">Paper (pdf)</a></li>
    <li><a href="{{ url_for('static', filename='dist/trajectory-poster.pdf') }}" target="_blank">Poster (pdf)</a></li>
    <li><a href="{{ url_for('static', filename='dist/trajectory-slides.pdf') }}" target="_blank">Slides (pdf)</a></li>
    <li><a href="https://github.com/jrouly/trajectory" target="_blank">Code (GitHub)</a></li>
  </ul>

  <!-- ------------------------------------------------------------------------------------------------------------ -->

  <h2>UA REU Empirical Software Engineering</h2>

  <p>
    <strong>Project Title:</strong>&nbsp;Usability and Suitability Survey of Features in Visual IDEs for Non-Programmers
  </p>

  <p>
    Summer 2014 I was engaged as an undergraduate researcher with the
    <a href="http://ua.edu" target="_blank">University of Alabama</a> and the
    <a href="http://www.nsf.gov" target="_blank">National Science Foundation</a> conducting research into software
    engineering theory and application with the <a href="http://reu.cs.ua.edu/" target="_blank">UA REU ESE</a> program.
  </p>

  <p>
    The project involved the systematic empirical study of user interfaces in visual language integrated development
    environments (IDEs). Along with
    <a href="http://www-ens.iro.umontreal.ca/~syriani" target="_blank">Dr. Eugene Syriani</a> we analyzed a set of
    visual language IDEs and developed formal metrics for comparison. The goal of this research was to understand the
    important positive and negative features of visual language IDEs in a formal setting.
  </p>

  <ul>
    <li><a href="https://doi.org/10.1145/2688204.2688207" target="_blank">ACM Digital Library</a></li>
    <li><a href="{{ url_for('static', filename='dist/ua-ese-reu-paper.pdf') }}" target="_blank">Paper (pdf)</a></li>
    <li><a href="{{ url_for('static', filename='dist/ua-ese-reu-slides.pdf') }}" target="_blank">Slides (pdf)</a></li>
  </ul>

  <!-- ------------------------------------------------------------------------------------------------------------ -->

  <h2>Amalthea REU</h2>

  <p>
    <strong>Project Title:</strong>&nbsp;Large-scale Clustering for Big Data Analytics: A MapReduce Implementation
    of Hierarchical Affinity Propagation
  </p>

  <p>
    Summer 2013 I was engaged as an undergraduate researcher with the
    <a href="http://www.fit.edu" target="_blank">Florida Institute of Technology</a> and the
    <a href="http://www.nsf.gov" target="_blank">National Science Foundation</a>
    conducting research into machine learning in theory and application with the
    <a href="http://www.amalthea-reu.org" target="_blank">Amalthea REU</a> program.
  </p>

  <p>
    The project involved architecting and implementing a Big Data scale data-mining framework. The application was
    built on existing free and open source software frameworks including
    <a href="http://hadoop.apache.org" target="_blank">Apache Hadoop</a> for MapReduce and distributed filesystem
    implementations, <a href="http://mahout.apache.org" target="_blank">Apache Mahout</a> libraries for mathematical
    support and algorithm benchmarking, and <a href="http://hive.apache.org" target="_blank">Apache Hive</a> for data
    warehousing and post-processing data manipulation.
  </p>

  <p>
    Specifically, we parallelized the exemplar-based clustering algorithm
    <a href="http://uai.sis.pitt.edu/papers/11/p238-givoni.pdf" target="_blank">Hierarchical Affinity Propagation</a>
    using a MapReduce framework. Preliminary results of running the distributed algorithm on
    <a href="http://aws.amazon.com/elasticmapreduce" target="_blank">AWS Elastic MapReduce (EMR)</a>
    service indicate superior performance as compared to competitive algorithms from the Apache Mahout libraries.
  </p>

  <ul>
    <li><a href="https://doi.org/10.1109/IC2E.2014.42" target="_blank">IEEE Xplore</a></li>
    <li><a href="{{ url_for('static', filename='dist/amalthea-paper.pdf') }}" target="_blank">Paper (pdf)</a></li>
    <li><a href="{{ url_for('static', filename='dist/amalthea-slides.pptx') }}" target="_blank">Slides (pptx)</a></li>
    <li><a href="{{ url_for('static', filename='dist/amalthea-poster.pdf') }}" target="_blank">Poster (pdf)</a></li>
    <li><a href="{{ url_for('static', filename='dist/amalthea-tech-report.pdf') }}" target="_blank">Tech Report (pdf)</a></li>
    <li><a href="https://github.com/jrouly/hap-with-map" target="_blank">Code (GitHub)</a></li>
  </ul>

{% endblock %}

web/templates/work.html
{% extends 'base.html' %}

{% block pagetitle %}
work
{% endblock %}

{% block content %}

  <h2>Zephyr AI</h2>

  <p>
    I am currently a software engineer with <a href="https://zephyrai.bio">Zephyr AI</a>.
    We use machine learning and precision medicine to identify novel biomarkers for chronic disease.
    I work with Python, TypeScript, Terraform, AWS, and many other technologies to support this goal.
  </p>


  <h2>Rally Health</h2>

  <p>
    I used to work at <a href="https://rallyhealth.com" target="_blank">Rally Health</a>.
    We built products that help users navigate the American healthcare system: finding high quality care, filling
    prescriptions, and understanding prices. I primarily wrote in
    <a href="https://www.scala-lang.org/" target="_blank">Scala</a> using the
    <a href="https://github.com/playframework/playframework" target="_blank">Play web framework</a>.
  </p>

  <h2>Harmonia</h2>

  <p>
    I was previously contracted with <a href="https://www.harmonia.com" target="_blank">Harmonia Holdings Group</a> as
    an independent Java programming consultant for the development of a learning classifier engine. My work included
    high level architecture design, user interface development, and software development to customer specification.
  </p>

  <h2>George Mason Honors College RTOC</h2>

  <p>
    During the fall semester of 2013, I worked with the
    <a href="https://honorscollege.gmu.edu/" target="_blank">George Mason University Honors College</a>
    as a part of the
    <a href="https://collegeresearch.gmu.edu/" target="_blank">Research, Technology, and Online Community (RTOC)</a>
    initiative with the goal of developing interactive online tools to support first year students engaging
    in scholarly research for the first time. While there, I lead the development of
    <a href="https://github.com/jrouly/research-questions" target="_blank">Research Questions</a> and
    <a href="https://github.com/jrouly/reading-scholarly-articles" target="_blank">Reading Scholarly Articles</a>. See
    <a href="{{  url_for('views.projects') }}">projects</a> for more information.
  </p>

{% endblock %}